-- ==============================================================================
-- SKEMA LENGKAP DATABASE SUPABASE - RANIAARCHI
-- Jalankan skrip SQL ini di Dashboard Supabase: Menu "SQL Editor" -> "New Query"
-- ==============================================================================

-- ==============================================================================
-- 1. TABEL PAPAN JUARA BEST PLAYER (LEADERBOARD)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.leaderboard (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  time_seconds INTEGER NOT NULL,
  score INTEGER NOT NULL,
  wrong_count INTEGER DEFAULT 0 NOT NULL,
  total_questions INTEGER DEFAULT 10 NOT NULL,
  badge TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Migrasi untuk tabel yang sudah ada sebelumnya
ALTER TABLE public.leaderboard ADD COLUMN IF NOT EXISTS wrong_count INTEGER DEFAULT 0 NOT NULL;

CREATE INDEX IF NOT EXISTS idx_leaderboard_ranking 
ON public.leaderboard (score DESC, wrong_count ASC, time_seconds ASC);

ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- Kebijakan RLS Leaderboard
DROP POLICY IF EXISTS "Semua orang dapat membaca leaderboard" ON public.leaderboard;
CREATE POLICY "Semua orang dapat membaca leaderboard" 
ON public.leaderboard FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Semua orang dapat menambahkan skor leaderboard" ON public.leaderboard;
CREATE POLICY "Semua orang dapat menambahkan skor leaderboard" 
ON public.leaderboard FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Admin dapat menghapus dan mereset leaderboard" ON public.leaderboard;
CREATE POLICY "Admin dapat menghapus dan mereset leaderboard" 
ON public.leaderboard FOR DELETE TO anon, authenticated USING (true);

-- Benchmark Awal 10 Pemain
INSERT INTO public.leaderboard (name, time_seconds, score, wrong_count, total_questions, badge)
VALUES
  ('Rania Archi', 38, 10, 0, 10, 'Juara Bertahan 👑'),
  ('Budi Pratama', 45, 10, 0, 10, 'Kilat Matematika ⚡'),
  ('Siti Aisyah', 52, 10, 0, 10, 'Bintang Hitung 🌟'),
  ('Ahmad Fauzi', 59, 10, 1, 10, NULL),
  ('Dewi Lestari', 67, 10, 1, 10, NULL),
  ('Reza Rahadian', 74, 10, 2, 10, NULL),
  ('Nadia Putri', 83, 10, 2, 10, NULL),
  ('Kevin Sanjaya', 91, 9, 1, 10, NULL),
  ('Putri Maharani', 98, 9, 2, 10, NULL),
  ('Dimas Anggara', 105, 9, 3, 10, NULL)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- 2. TABEL SOAL TAMBAHAN DARI ADMIN/GURU (QUESTIONS)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  subtext TEXT NOT NULL DEFAULT 'Soal Tambahan Guru',
  options JSONB NOT NULL,
  explanation TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Semua orang dapat membaca soal" ON public.questions;
CREATE POLICY "Semua orang dapat membaca soal" 
ON public.questions FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Admin dapat menambah soal" ON public.questions;
CREATE POLICY "Admin dapat menambah soal" 
ON public.questions FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Admin dapat menghapus soal" ON public.questions;
CREATE POLICY "Admin dapat menghapus soal" 
ON public.questions FOR DELETE TO anon, authenticated USING (true);

-- ==============================================================================
-- 3. TABEL AKUN SISWA / PENGGUNA (STUDENTS)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.students (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  grade TEXT DEFAULT 'Kelas 4 SD' NOT NULL,
  pin TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Semua orang dapat membaca akun siswa" ON public.students;
CREATE POLICY "Semua orang dapat membaca akun siswa" 
ON public.students FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Admin dapat menambah akun siswa" ON public.students;
CREATE POLICY "Admin dapat menambah akun siswa" 
ON public.students FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Admin dapat menghapus akun siswa" ON public.students;
CREATE POLICY "Admin dapat menghapus akun siswa" 
ON public.students FOR DELETE TO anon, authenticated USING (true);

-- Data Awal Siswa
INSERT INTO public.students (name, grade, pin)
VALUES
  ('Rania Archi', 'Kelas 4 SD', '1234'),
  ('Budi Pratama', 'Kelas 4 SD', '1234'),
  ('Siti Aisyah', 'Kelas 4 SD', '1234'),
  ('Ahmad Fauzi', 'Kelas 4 SD', NULL),
  ('Dewi Lestari', 'Kelas 4 SD', NULL)
ON CONFLICT DO NOTHING;
